services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    command: sh -c "npm run test && npm start"

volumes:
  mongo-data:
